version: '3'

services:
  mongo:
    container_name: "mongo-bank-simulator-service"
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - "27017:27017"